"""
Acesso ao banco de dados.

Duas implementações com a mesma interface:
  RepositorioSQLite   banco local em arquivo (padrão; não precisa de internet)
  RepositorioSupabase PostgreSQL do Supabase (precisa do .env)

Escolha pela variável de ambiente BANCO ("sqlite" ou "supabase") ou pelo
argumento de obter_repositorio(). As duas usam o mesmo schema.sql.

Interface:
  substituir_tudo(tabelas)   carga: apaga e grava todas as tabelas
  esta_vazio()               True se ainda não houve carga
  carregar_dados()           professores, disciplinas, horários e alocações
  carregar_grade(semestre)   linhas da GRA_GRADE_HORARIA de um semestre
  salvar_grade(semestre, linhas)  substitui a grade do semestre
  semestres()                semestres gravados e quantidade de linhas
"""
import os
import sqlite3

from dotenv import load_dotenv

load_dotenv()

PASTA = os.path.dirname(os.path.abspath(__file__))
ARQUIVO_SCHEMA = os.path.join(PASTA, "schema.sql")
ARQUIVO_SQLITE = os.path.join(PASTA, "grade.db")

ORDEM_TABELAS = ["PRO_PROFESSOR", "DIS_DISCIPLINA", "HOR_HORARIO", "ALO_ALOCACAO", "GRA_GRADE_HORARIA"]


def _montar_alocacoes(alocacoes, professores, disciplinas):
    """Junta professor e disciplina em cada alocação (mesmo formato do select com join do Supabase)."""
    pro = {p["PRO_ID"]: p for p in professores}
    dis = {d["DIS_ID"]: d for d in disciplinas}
    saida = []
    for a in sorted(alocacoes, key=lambda a: a["ALO_ID"]):
        d = dict(dis[a["DIS_ID"]])
        d["DIS_ELETIVA"] = bool(d.get("DIS_ELETIVA"))
        saida.append({"ALO_ID": a["ALO_ID"], "PRO_ID": a["PRO_ID"], "DIS_ID": a["DIS_ID"],
                      "PRO_NOME": pro[a["PRO_ID"]]["PRO_NOME"], "DIS_DISCIPLINA": d})
    return saida


def montar_dados(tabelas):
    """Mesmo formato de carregar_dados(), direto das tabelas da carga (sem banco)."""
    disciplinas = [dict(d) for d in tabelas["DIS_DISCIPLINA"]]
    return {"professores": tabelas["PRO_PROFESSOR"], "disciplinas": disciplinas,
            "horarios": sorted(tabelas["HOR_HORARIO"], key=lambda h: h["HOR_ID"]),
            "alocacoes": _montar_alocacoes(tabelas["ALO_ALOCACAO"], tabelas["PRO_PROFESSOR"], disciplinas)}


class RepositorioSQLite:
    def __init__(self, caminho=ARQUIVO_SQLITE):
        self.caminho = caminho
        self.descricao = f"SQLite ({os.path.basename(caminho)})"
        self.criar_esquema()

    def _conectar(self):
        con = sqlite3.connect(self.caminho)
        con.row_factory = sqlite3.Row
        con.execute("PRAGMA foreign_keys = ON")
        return con

    def criar_esquema(self):
        with open(ARQUIVO_SCHEMA, encoding="utf-8") as f:
            sql = f.read()
        # Única diferença de sintaxe entre PostgreSQL e SQLite neste schema.
        sql = sql.replace("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT")
        with self._conectar() as con:
            con.executescript(sql)

    def _todas(self, con, tabela):
        return [dict(r) for r in con.execute(f'SELECT * FROM "{tabela}"')]

    def substituir_tudo(self, tabelas):
        with self._conectar() as con:
            for tabela in reversed(ORDEM_TABELAS):
                con.execute(f'DELETE FROM "{tabela}"')
            for tabela in ORDEM_TABELAS:
                linhas = tabelas.get(tabela, [])
                if not linhas:
                    continue
                colunas = list(linhas[0])
                sql = (f'INSERT INTO "{tabela}" ({", ".join(chr(34) + c + chr(34) for c in colunas)}) '
                       f'VALUES ({", ".join("?" for _ in colunas)})')
                con.executemany(sql, [tuple(l[c] for c in colunas) for l in linhas])

    def esta_vazio(self):
        with self._conectar() as con:
            return con.execute('SELECT COUNT(*) FROM "ALO_ALOCACAO"').fetchone()[0] == 0

    def carregar_dados(self):
        with self._conectar() as con:
            professores = self._todas(con, "PRO_PROFESSOR")
            disciplinas = self._todas(con, "DIS_DISCIPLINA")
            horarios = sorted(self._todas(con, "HOR_HORARIO"), key=lambda h: h["HOR_ID"])
            alocacoes = self._todas(con, "ALO_ALOCACAO")
        for d in disciplinas:
            d["DIS_ELETIVA"] = bool(d["DIS_ELETIVA"])
        return {"professores": professores, "disciplinas": disciplinas, "horarios": horarios,
                "alocacoes": _montar_alocacoes(alocacoes, professores, disciplinas)}

    def carregar_grade(self, semestre):
        with self._conectar() as con:
            return [dict(r) for r in con.execute(
                'SELECT "GRA_SEMESTRE", "ALO_ID", "HOR_ID" FROM "GRA_GRADE_HORARIA" '
                'WHERE "GRA_SEMESTRE" = ? ORDER BY "ALO_ID", "HOR_ID"', (semestre,))]

    def salvar_grade(self, semestre, linhas):
        with self._conectar() as con:
            con.execute('DELETE FROM "GRA_GRADE_HORARIA" WHERE "GRA_SEMESTRE" = ?', (semestre,))
            con.executemany('INSERT INTO "GRA_GRADE_HORARIA" ("GRA_SEMESTRE", "ALO_ID", "HOR_ID") VALUES (?, ?, ?)',
                            [(semestre, l["ALO_ID"], l["HOR_ID"]) for l in linhas])
        return len(linhas)

    def semestres(self):
        with self._conectar() as con:
            return [{"semestre": r[0], "linhas": r[1]} for r in con.execute(
                'SELECT "GRA_SEMESTRE", COUNT(*) FROM "GRA_GRADE_HORARIA" GROUP BY "GRA_SEMESTRE" ORDER BY 1')]


class RepositorioSupabase:
    """
    Mesma interface, usando o cliente do Supabase.

    As tabelas precisam ter sido criadas com schema.sql (ou migracao_supabase.sql,
    se o projeto ainda tiver as tabelas antigas DI_/HO_).
    """

    def __init__(self, cliente=None):
        if cliente is None:
            from database.connection.connect import conectar_supabase
            cliente = conectar_supabase()
        self.cliente = cliente
        self.descricao = "Supabase"

    def _todas(self, tabela):
        return self.cliente.table(tabela).select("*").execute().data

    def substituir_tudo(self, tabelas):
        for tabela in reversed(ORDEM_TABELAS):
            chave = {"GRA_GRADE_HORARIA": "GRA_ID", "ALO_ALOCACAO": "ALO_ID", "HOR_HORARIO": "HOR_ID",
                     "DIS_DISCIPLINA": "DIS_ID", "PRO_PROFESSOR": "PRO_ID"}[tabela]
            self.cliente.table(tabela).delete().gte(chave, 0).execute()
        for tabela in ORDEM_TABELAS:
            linhas = tabelas.get(tabela, [])
            if linhas:
                self.cliente.table(tabela).insert(linhas).execute()

    def esta_vazio(self):
        r = self.cliente.table("ALO_ALOCACAO").select("ALO_ID", count="exact").limit(1).execute()
        return not r.count

    def carregar_dados(self):
        professores = self._todas("PRO_PROFESSOR")
        disciplinas = self._todas("DIS_DISCIPLINA")
        horarios = sorted(self._todas("HOR_HORARIO"), key=lambda h: h["HOR_ID"])
        alocacoes = self._todas("ALO_ALOCACAO")
        return {"professores": professores, "disciplinas": disciplinas, "horarios": horarios,
                "alocacoes": _montar_alocacoes(alocacoes, professores, disciplinas)}

    def carregar_grade(self, semestre):
        return (self.cliente.table("GRA_GRADE_HORARIA").select("GRA_SEMESTRE, ALO_ID, HOR_ID")
                .eq("GRA_SEMESTRE", semestre).order("ALO_ID").order("HOR_ID").execute().data)

    def salvar_grade(self, semestre, linhas):
        self.cliente.table("GRA_GRADE_HORARIA").delete().eq("GRA_SEMESTRE", semestre).execute()
        if linhas:
            self.cliente.table("GRA_GRADE_HORARIA").insert(
                [{"GRA_SEMESTRE": semestre, "ALO_ID": l["ALO_ID"], "HOR_ID": l["HOR_ID"]} for l in linhas]).execute()
        return len(linhas)

    def semestres(self):
        contagem = {}
        for r in self.cliente.table("GRA_GRADE_HORARIA").select("GRA_SEMESTRE").execute().data:
            contagem[r["GRA_SEMESTRE"]] = contagem.get(r["GRA_SEMESTRE"], 0) + 1
        return [{"semestre": s, "linhas": n} for s, n in sorted(contagem.items())]


def obter_repositorio(banco=None, caminho_sqlite=None):
    """banco: 'sqlite' ou 'supabase'. Sem argumento, usa a variável BANCO (padrão sqlite)."""
    banco = (banco or os.getenv("BANCO") or "sqlite").lower()
    if banco == "supabase":
        return RepositorioSupabase()
    if banco == "sqlite":
        return RepositorioSQLite(caminho_sqlite or os.getenv("BANCO_SQLITE") or ARQUIVO_SQLITE)
    raise ValueError(f"BANCO desconhecido: {banco!r} (use sqlite ou supabase)")
