-- Modelo físico do banco da grade horária (PostgreSQL / Supabase).
--
-- Padrão de nomes (correção da professora no card Modelo de Dados):
--   tabela  = <SIGLA de 3 letras>_<ENTIDADE>   ex.: PRO_PROFESSOR
--   coluna  = <SIGLA>_<ATRIBUTO>               ex.: PRO_NOME
--   chave estrangeira mantém o nome da coluna de origem (PRO_ID, DIS_ID...).
--
-- Os nomes ficam entre aspas porque o Supabase (PostgREST) diferencia
-- maiúsculas de minúsculas. O mesmo arquivo é usado pelo SQLite local
-- (database/repositorio.py troca a linha de IDENTITY por AUTOINCREMENT).

-- Professor que ministra disciplinas.
CREATE TABLE IF NOT EXISTS "PRO_PROFESSOR" (
    "PRO_ID"        INTEGER PRIMARY KEY,
    "PRO_NOME"      VARCHAR(120) NOT NULL UNIQUE,
    "PRO_MATRICULA" VARCHAR(20)
);

-- Disciplina do perfil curricular CP21.
-- DIS_PERIODO: período em que a disciplina é ofertada (define o conflito "pleno").
-- DIS_CARGA_HORARIA: horas no semestre; faixas por semana = carga / 15.
-- DIS_ELETIVA: eletivas do mesmo período podem coincidir entre si (o aluno escolhe).
CREATE TABLE IF NOT EXISTS "DIS_DISCIPLINA" (
    "DIS_ID"            INTEGER PRIMARY KEY,
    "DIS_CODIGO"        VARCHAR(10)  NOT NULL UNIQUE,
    "DIS_DESCRICAO"     VARCHAR(120) NOT NULL,
    "DIS_PERIODO"       SMALLINT     NOT NULL CHECK ("DIS_PERIODO" BETWEEN 1 AND 10),
    "DIS_CARGA_HORARIA" SMALLINT     NOT NULL CHECK ("DIS_CARGA_HORARIA" > 0),
    "DIS_ELETIVA"       BOOLEAN      NOT NULL DEFAULT FALSE
);

-- Faixa de aula de 50 minutos no padrão da POLI: dia 2 (segunda) a 6 (sexta)
-- e faixa A (07:10) a L (16:20). Ex.: dia 2 + faixa C = "2C" = segunda 08:50.
CREATE TABLE IF NOT EXISTS "HOR_HORARIO" (
    "HOR_ID"     INTEGER PRIMARY KEY,
    "HOR_DIA"    SMALLINT NOT NULL CHECK ("HOR_DIA" BETWEEN 2 AND 6),
    "HOR_FAIXA"  CHAR(1)  NOT NULL,
    "HOR_INICIO" VARCHAR(5) NOT NULL,
    "HOR_FIM"    VARCHAR(5) NOT NULL,
    UNIQUE ("HOR_DIA", "HOR_FAIXA")
);

-- Alocação professor x disciplina (quem ministra o quê).
CREATE TABLE IF NOT EXISTS "ALO_ALOCACAO" (
    "ALO_ID" INTEGER PRIMARY KEY,
    "PRO_ID" INTEGER NOT NULL REFERENCES "PRO_PROFESSOR" ("PRO_ID"),
    "DIS_ID" INTEGER NOT NULL REFERENCES "DIS_DISCIPLINA" ("DIS_ID"),
    UNIQUE ("PRO_ID", "DIS_ID")
);

-- Grade horária: cada linha diz que a alocação ocupa uma faixa no semestre.
-- Professor e disciplina vêm pela alocação (ALO_ID).
CREATE TABLE IF NOT EXISTS "GRA_GRADE_HORARIA" (
    "GRA_ID"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "GRA_SEMESTRE" VARCHAR(20) NOT NULL,
    "ALO_ID"       INTEGER NOT NULL REFERENCES "ALO_ALOCACAO" ("ALO_ID"),
    "HOR_ID"       INTEGER NOT NULL REFERENCES "HOR_HORARIO" ("HOR_ID"),
    UNIQUE ("GRA_SEMESTRE", "ALO_ID", "HOR_ID")
);

CREATE INDEX IF NOT EXISTS "IDX_GRA_SEMESTRE" ON "GRA_GRADE_HORARIA" ("GRA_SEMESTRE");
